### ISSUE TITLE
Missing Python version

### ISSUE THREAD

**Issue by jtpio** [jupyter-xeus/xeus-python#649]
Noticed on Binder:

- repo: https://github.com/jupyter/notebook/blob/main/binder/environment.yml
- link: https://mybinder.org/v2/gh/jupyter/notebook/main?urlpath=tree

```yaml
name: notebook
channels:
  - conda-forge
dependencies:
  - ipywidgets=8
  - jupyterlab=4
  - jupyterlab-language-pack-fr-FR
  - matplotlib
  - numpy
  - nodejs=20
  - python >=3.10,<3.11
  - xeus-python
```

It looks like the Python version is missing, and shows "Python ." instead.

With JupyterLab:

![Image](https://github.com/user-attachments/assets/702d7738-cc85-40e2-995a-554ac8b3f64c)

With Jupyter Notebook:

![Image](https://github.com/user-attachments/assets/d889d66d-271d-407b-a4a2-5f7552febc51)
